version: "3.8"
services:
  frontend:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/api_front:/usr/local/apache2/htdocs/GraduationProject/api_front
      - ./frontend/CSS:/usr/local/apache2/htdocs/GraduationProject/CSS
    networks:
      - frontend-net

  backend:
    build: ./backend
    ports:
      - "8080:80"
    environment:
      DB_HOST: database
      DB_NAME: smart_bins_system
      DB_USER: root
      DB_PASS: rootpassword
    depends_on:
      - database
    networks:
      - frontend-net
      - backend-net
    

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_bins_system
    ports:
      - "3306:3306"
    volumes:
      - ./backend/Database/smart_bins_system.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net

networks:
  frontend-net:
  backend-net:






  

  